-- Hale.WaiExtra — WAI middleware and utilities
-- Ports Haskell's wai-extra package
import Hale.WaiExtra.Network.Wai.Header
import Hale.WaiExtra.Network.Wai.Request
import Hale.WaiExtra.Network.Wai.UrlMap
import Hale.WaiExtra.Network.Wai.Middleware.AcceptOverride
import Hale.WaiExtra.Network.Wai.Middleware.AddHeaders
import Hale.WaiExtra.Network.Wai.Middleware.Autohead
import Hale.WaiExtra.Network.Wai.Middleware.CleanPath
import Hale.WaiExtra.Network.Wai.Middleware.CombineHeaders
import Hale.WaiExtra.Network.Wai.Middleware.ForceDomain
import Hale.WaiExtra.Network.Wai.Middleware.ForceSSL
import Hale.WaiExtra.Network.Wai.Middleware.HealthCheckEndpoint
import Hale.WaiExtra.Network.Wai.Middleware.Local
import Hale.WaiExtra.Network.Wai.Middleware.MethodOverride
import Hale.WaiExtra.Network.Wai.Middleware.MethodOverridePost
import Hale.WaiExtra.Network.Wai.Middleware.Rewrite
import Hale.WaiExtra.Network.Wai.Middleware.Routed
import Hale.WaiExtra.Network.Wai.Middleware.Select
import Hale.WaiExtra.Network.Wai.Middleware.StreamFile
import Hale.WaiExtra.Network.Wai.Middleware.StripHeaders
import Hale.WaiExtra.Network.Wai.Middleware.Timeout
import Hale.WaiExtra.Network.Wai.Middleware.ValidateHeaders
import Hale.WaiExtra.Network.Wai.Middleware.Vhost
import Hale.WaiExtra.Network.Wai.Middleware.HttpAuth
import Hale.WaiExtra.Network.Wai.Middleware.RequestSizeLimit
import Hale.WaiExtra.Network.Wai.Middleware.RealIp
import Hale.WaiExtra.Network.Wai.Middleware.Jsonp
import Hale.WaiExtra.Network.Wai.Middleware.Approot
import Hale.WaiExtra.Network.Wai.Middleware.RequestLogger
import Hale.WaiExtra.Network.Wai.Middleware.Gzip
import Hale.WaiExtra.Network.Wai.Middleware.RequestLogger.JSON
import Hale.WaiExtra.Network.Wai.Middleware.RequestSizeLimit.Internal
import Hale.WaiExtra.Network.Wai.Parse
import Hale.WaiExtra.Network.Wai.Test
import Hale.WaiExtra.Network.Wai.Test.Internal
import Hale.WaiExtra.Network.Wai.EventSource
import Hale.WaiExtra.Network.Wai.EventSource.EventStream
